Added log check

diff --git a/.github/workflows/security-scan.yml b/.github/workflows/security-scan.yml
--- a/.github/workflows/security-scan.yml
+++ b/.github/workflows/security-scan.yml
@@ -28,7 +28,16 @@ jobs:
         -H "user-email: ci@bot.com" \
         -F "file=@package.json")
 
+
+        echo "===== RESPONSE ====="
         echo "Response: $RESPONSE"
+
+        ERROR=$(echo $RESPONSE | jq -r '.error.message')
+
+        if ["$ERROR" != "null"]; then
+          echo "❌ API Error: $ERROR"
+          exit 1
+        fi
 
         RISK=$(echo $RESPONSE | jq -r '.summary.riskSeverity')
 
